name: sportfreunde-eschbach
services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - /home/destroflyer/sportfreunde-eschbach/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 0
    restart: always
  app:
    image: wordpress:6.5.4-php8.3-apache
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: $DB_ROOT_PASSWORD
      WORDPRESS_DB_NAME: sportfreunde-eschbach
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_AUTH_KEY: $AUTH_KEY
      WORDPRESS_AUTH_SALT: $AUTH_SALT
      WORDPRESS_SECURE_AUTH_KEY: $SECURE_AUTH_KEY
      WORDPRESS_SECURE_AUTH_SALT: $SECURE_AUTH_SALT
      WORDPRESS_LOGGED_IN_KEY: $LOGGED_IN_KEY
      WORDPRESS_LOGGED_IN_SALT: $LOGGED_IN_SALT
      WORDPRESS_NONCE_KEY: $NONCE_KEY
      WORDPRESS_NONCE_SALT: $NONCE_SALT
    volumes:
      - /home/destroflyer/sportfreunde-eschbach/wp-content:/var/www/html/wp-content
    ports:
      - "127.0.0.1:1500:80"
    restart: always
